
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =             416
     no. of nonzeroes in lower triangle of a =            5928
     no. of nonzeroes in the factor l        =           23242
     ratio of nonzeroes in factor (min/max)  =          0.4845
     number of super nodes                   =              18
     maximum order of a front matrix         =              84
     maximum size of a front matrix          =            3570
     maximum size of a front trapezoid       =            2750
     METIS reordering method used 
     no. of floating point ops for factor    =      9.3952D+05
     no. of floating point ops for solve     =      7.1952D+04
     ratio of flops for factor (min/max)     =          0.6210
     ratio of allocated memory (max/min)     =          1.1029
     number of positive pivots               =             416
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000083
     time (cpu & wall) for ordering          =        0.000000        0.002568
     time (cpu & wall) for other matrix prep =        0.000000        0.002615
     time (cpu & wall) for value input       =        0.000000        0.000065
     time (cpu & wall) for matrix distrib.   =        0.046875        0.004473

     no input or output performed

  Solver Memory allocated on core    0       =        0.365 MB
  Solver Memory allocated on core    1       =        0.350 MB
  Solver Memory allocated on core    2       =        0.372 MB
  Solver Memory allocated on core    3       =        0.338 MB
  Total Solver Memory allocated by all cores =        1.425 MB

