
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          303279
     no. of nonzeroes in lower triangle of a =        12701586
     no. of nonzeroes in the factor l        =       309690330
     ratio of nonzeroes in factor (min/max)  =          0.6246
     number of super nodes                   =            9676
     maximum order of a front matrix         =            6969
     maximum size of a front matrix          =        24286965
     maximum size of a front trapezoid       =        18617655
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      9.1064D+11
     no. of floating point ops for solve     =      1.2090D+09
     ratio of flops for factor (min/max)     =          0.8187
     ratio of allocated memory (max/min)     =          1.4136
     number of positive pivots               =          303275
     number of negative pivots               =               4
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.015625        0.021377
     time (cpu & wall) for ordering          =        0.515625        0.505441
     time (cpu & wall) for other matrix prep =        0.093750        0.089798
     time (cpu & wall) for value input       =        0.046875        0.048849
     time (cpu & wall) for matrix distrib.   =        0.296875        0.304238
     time (cpu & wall) for numeric factor    =        7.171875        7.202512
     computational rate (gflops) for factor  =      126.973104      126.433003
     time (cpu & wall) for numeric solve     =        0.171875        0.181043
     computational rate (gflops) for solve   =        7.034059        6.677870
     effective I/O rate (GB/sec) for solve   =       26.205993       24.878979

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        819200.        6. MB        800876.        6. MB
                95-   1        786432.        6. MB        758628.        6. MB
                95-   2        557056.        4. MB        525335.        4. MB
                95-   3       1081344.        8. MB       1065620.        8. MB

                -------     ----------     --------     ----------     --------
                Totals:       3244032.       25. MB       3150459.       24. MB


  Solver Memory allocated on core    0       =      904.287 MB
  Solver Memory allocated on core    1       =      887.864 MB
  Solver Memory allocated on core    2       =      728.695 MB
  Solver Memory allocated on core    3       =     1030.047 MB
  Total Solver Memory allocated by all cores =     3550.893 MB

