/CLEAR,NOSTART  
/FILNAME,pdefilter,1
/CWD,'C:\Users\samue\OSR\shared'
    
/PREP7  
CDREAD,DB,'model','cdb' 
DDELE,ALL,ALL   
FDELE,ALL,ALL   
SFDELE,ALL,ALL  
BFDELE,ALL,ALL  
BFEDELE,ALL,ALL 
ETCHG,STT   
MP,KXX,1,1  
MP,DENS,1,1 
MP,C,1,1
FINISH  
    
/SOLU   
ANTYPE,TRANS
TRNOPT,FULL 
TIMINT,ON   
TINTP,,,,1.0
LUMPM,OFF   
NSUBST,1
TIME,1  
WRFULL,1
SOLVE   
FINISH  
    
*SMAT,Kt,D,IMPORT,FULL,pdefilter.full,STIFF 
*SMAT,Mt,D,IMPORT,FULL,pdefilter.full,DAMP  
*VEC,Map,I,IMPORT,FULL,pdefilter.full,BACK  
*EXPORT,Kt,MMF,K_pde.mtx
*EXPORT,Mt,MMF,M_pde.mtx
*EXPORT,Map,MMF,map_pde.mtx 
